### PR TITLE
Add env_logger to tests.

### PR DESCRIPTION
**Pull request by glasswings**
The `log` crate needs to be initialized with a backend or it won't report any messages.  

This adds [env_log hooks](https://github.com/rust-lang-nursery/log/blob/e00bc558e391519ef41198ee44eca1f767af20af/README.md) to the tests so that `RUST_LOG=coio=trace cargo test` generates lots of output instead of none.

### CODE REVIEW

**Comment by zonyitoo** [comment]
Yes, but .. is it necessary to commit this to the repo? Because these is used for debugging, not testing.

**Comment by lhecker** [comment]
I think it's alright actually… But if possible I'd move the env_logger to `src/lib.rs`, like this:

```
#[cfg(test)]
extern crate env_logger;
```

**Comment by lhecker** [comment]
@glasswings One of us was strongly against this PR (due to the added code) and one was somewhat for it. So... I'll close this PR for now. Still thanks! :blush:

**Comment by lhecker** [comment]
Ah before I forget it: You can now use `::env_logger::init().unwrap();` in any test on `origin/master` and it will work.

**Pull request closed without merging**
