### PR TITLE
[#19] Implemented lock-free Processor::resume()

### PR DESCRIPTION
**Pull request by lhecker**
This commit adds a new method Processor::block_with() which allows one to pass a FnMut() to be executed after the context switch in block() is over.
This can be used to e.g. release resources on behalf of the current coroutine and is now being used in the MPSC queues to drop() the MutexGuards after the coroutine has been safely parked.

### CODE REVIEW

**Comment by zonyitoo** [comment]
Looks good. Have you test it? You may tries to increase the number of worker threads.

**Comment by lhecker** [comment]
@zonyitoo I did a force push just now which includes such a test: https://github.com/lhecker/coio-rs/blob/f7dd5277689f5f8f4e0345bd9f00ed181e590650/src/sync/mpsc.rs#L286-L339

**Comment by zonyitoo** [comment]
I am trying to use your `block_with` function in `Scheduler`, all looks good.

**Comment by zonyitoo** [comment]
I cannot merge it right now, because your code would break the implementation of `Scheduler::wait_event` and `Scheduler::timeout_ms`. I think this can be merged after we find out the cause of low performance.

I have profiled on it, and I suspected the cost of `Scheduler::wait_event` and `IoHandler::ready` is the main reason, which are the most frequently called functions, but they use lock-free queues to send/recv events and coroutines.

**Comment by lhecker** [comment]
@zonyitoo Is the problem with `Scheduler::wait_event` about the fact that the `IoHandlerMessage` must be moved in order for it to be sent?
You can try moving the whole implementation (except for the beginning if clause) into the closure instead (since it's the same thread the performance should be equal): https://gist.github.com/lhecker/a5b38f5a2f180d86eaf4

**Comment by lhecker** [comment]
Closed by 1fa3afbea85c1334a6c0552b9bb0d4a711b7b44f

**Pull request closed without merging**
